//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_PAYMENT
    {
        public int PayMentID { get; set; }
        public Nullable<int> CusNo { get; set; }
        public Nullable<int> SubTotal { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> Cash { get; set; }
        public Nullable<int> Card { get; set; }
        public Nullable<int> IsCredit { get; set; }
        public Nullable<int> IsDebit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int UpdateBy { get; set; }
    }
}
