//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ABN { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Web { get; set; }
        public string Logan { get; set; }
        public string Note { get; set; }
    }
}
