//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Payment { get; set; }
        public Nullable<int> Change { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<long> InvoiceByCardID { get; set; }
        public Nullable<int> CashOut { get; set; }
        public Nullable<int> Seat { get; set; }
        public Nullable<int> Account { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> FloorType { get; set; }
        public Nullable<int> PDA { get; set; }
    }
}
