//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int ID { get; set; }
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public string OrderNumber { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> KeyItem { get; set; }
        public int Status { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> Seat { get; set; }
        public Nullable<int> DynId { get; set; }
        public Nullable<int> PrintType { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> ItemTKA { get; set; }
    }
}
