//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_OPEN_ITEM
    {
        public int dynID { get; set; }
        public string ItemNameShort { get; set; }
        public string ItemNameDesc { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> PrinterID { get; set; }
        public Nullable<int> PrintType { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
