//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POSEZ2UEntities : DbContext
    {
        public POSEZ2UEntities()
            : base("name=POSEZ2UEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACC_PAYMENT> ACC_PAYMENT { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CATALOGUE> CATALOGUEs { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<CONFIG> CONFIGs { get; set; }
        public virtual DbSet<CONFIG_SAVE_DATA> CONFIG_SAVE_DATA { get; set; }
        public virtual DbSet<DATABASE_BACKUP> DATABASE_BACKUP { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<FLOOR> FLOORs { get; set; }
        public virtual DbSet<INVOICE> INVOICEs { get; set; }
        public virtual DbSet<INVOICE_BY_CARD> INVOICE_BY_CARD { get; set; }
        public virtual DbSet<INVOICE_DETAIL> INVOICE_DETAIL { get; set; }
        public virtual DbSet<INVOICE_DETAIL_HISTORY> INVOICE_DETAIL_HISTORY { get; set; }
        public virtual DbSet<INVOICE_DETAIL_MODIFIRE> INVOICE_DETAIL_MODIFIRE { get; set; }
        public virtual DbSet<INVOICE_DETAIL_MODIFIRE_HISTORY> INVOICE_DETAIL_MODIFIRE_HISTORY { get; set; }
        public virtual DbSet<INVOICE_HISTORY> INVOICE_HISTORY { get; set; }
        public virtual DbSet<MAP_CATEGORY_TO_CATALOGUE> MAP_CATEGORY_TO_CATALOGUE { get; set; }
        public virtual DbSet<MAP_MODIFIRE_TO_PRODUCT> MAP_MODIFIRE_TO_PRODUCT { get; set; }
        public virtual DbSet<MAP_PRODUCT_TO_CATEGORY> MAP_PRODUCT_TO_CATEGORY { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<MODIFIRE> MODIFIREs { get; set; }
        public virtual DbSet<MODIFIRE_PRICE> MODIFIRE_PRICE { get; set; }
        public virtual DbSet<ORDER> ORDERs { get; set; }
        public virtual DbSet<ORDER_DATE> ORDER_DATE { get; set; }
        public virtual DbSet<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public virtual DbSet<ORDER_DETAIL_DATE> ORDER_DETAIL_DATE { get; set; }
        public virtual DbSet<ORDER_DETAIL_MODIFIRE> ORDER_DETAIL_MODIFIRE { get; set; }
        public virtual DbSet<ORDER_DETAIL_MODIFIRE_DATE> ORDER_DETAIL_MODIFIRE_DATE { get; set; }
        public virtual DbSet<ORDER_OPEN_ITEM> ORDER_OPEN_ITEM { get; set; }
        public virtual DbSet<ORDER_OPEN_ITEM_ALL> ORDER_OPEN_ITEM_ALL { get; set; }
        public virtual DbSet<PAYMENT_INVOICE_HISTORY> PAYMENT_INVOICE_HISTORY { get; set; }
        public virtual DbSet<PAYMENT_INVOICE_HISTORY_ALL> PAYMENT_INVOICE_HISTORY_ALL { get; set; }
        public virtual DbSet<PAYMENT_TYPE> PAYMENT_TYPE { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<PRINT_JOB> PRINT_JOB { get; set; }
        public virtual DbSet<PRINTE_JOB_DETAIL> PRINTE_JOB_DETAIL { get; set; }
        public virtual DbSet<PRINTER> PRINTERs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCT_PRICE> PRODUCT_PRICE { get; set; }
        public virtual DbSet<SEAT> SEATs { get; set; }
        public virtual DbSet<SHIFT_HISTORY> SHIFT_HISTORY { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<SUB_MENU> SUB_MENU { get; set; }
        public virtual DbSet<VOID_ITEM_HISTORY> VOID_ITEM_HISTORY { get; set; }
        public virtual DbSet<TableTemp> TableTemps { get; set; }
        public virtual DbSet<VIEW_INVOICE_ALL> VIEW_INVOICE_ALL { get; set; }
        public virtual DbSet<VIEW_INVOICE_DETAIL_ALL> VIEW_INVOICE_DETAIL_ALL { get; set; }
        public virtual DbSet<VIEW_INVOICE_DETAIL_MODIFIRE_ALL> VIEW_INVOICE_DETAIL_MODIFIRE_ALL { get; set; }
        public virtual DbSet<VIEW_ORDER_ALL> VIEW_ORDER_ALL { get; set; }
        public virtual DbSet<VIEW_ORDER_DETAIL_ALL> VIEW_ORDER_DETAIL_ALL { get; set; }
        public virtual DbSet<VIEW_ORDER_DETAIL_MODIFIRE_ALL> VIEW_ORDER_DETAIL_MODIFIRE_ALL { get; set; }
        public virtual DbSet<VIEW_PAYMENT_INVOICE_HISTORY_ALL> VIEW_PAYMENT_INVOICE_HISTORY_ALL { get; set; }
        public virtual DbSet<view_report_invoice> view_report_invoice { get; set; }
    
        public virtual ObjectResult<pos_th_GetAllListCategoryByCatalogue_Result> pos_th_GetAllListCategoryByCatalogue(Nullable<int> catalogueid)
        {
            var catalogueidParameter = catalogueid.HasValue ?
                new ObjectParameter("catalogueid", catalogueid) :
                new ObjectParameter("catalogueid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetAllListCategoryByCatalogue_Result>("pos_th_GetAllListCategoryByCatalogue", catalogueidParameter);
        }
    
        public virtual ObjectResult<pos_th_GetAllListProductByCategory_Result> pos_th_GetAllListProductByCategory(Nullable<int> categoryid)
        {
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetAllListProductByCategory_Result>("pos_th_GetAllListProductByCategory", categoryidParameter);
        }
    
        public virtual ObjectResult<pos_th_GetListModifire_Result> pos_th_GetListModifire(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetListModifire_Result>("pos_th_GetListModifire", productIDParameter);
        }
    
        public virtual ObjectResult<pos_th_GetListModifireToProduct_Result> pos_th_GetListModifireToProduct(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetListModifireToProduct_Result>("pos_th_GetListModifireToProduct", productIDParameter);
        }
    
        public virtual int pos_th_SaveDataMapCategoryToCatalogue(Nullable<int> catalogueid, Nullable<int> userid)
        {
            var catalogueidParameter = catalogueid.HasValue ?
                new ObjectParameter("catalogueid", catalogueid) :
                new ObjectParameter("catalogueid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pos_th_SaveDataMapCategoryToCatalogue", catalogueidParameter, useridParameter);
        }
    
        public virtual int pos_th_SaveDataMapProductToCategory(Nullable<int> categoryid, Nullable<int> userid)
        {
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pos_th_SaveDataMapProductToCategory", categoryidParameter, useridParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        [DbFunction("POSEZ2UEntities", "getProductByCategory")]
        public virtual IQueryable<getProductByCategory_Result> getProductByCategory(Nullable<int> categoryid)
        {
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getProductByCategory_Result>("[POSEZ2UEntities].[getProductByCategory](@categoryid)", categoryidParameter);
        }
    
        [DbFunction("POSEZ2UEntities", "fxnExample")]
        public virtual IQueryable<fxnExample_Result> fxnExample(Nullable<int> parameter1)
        {
            var parameter1Parameter = parameter1.HasValue ?
                new ObjectParameter("Parameter1", parameter1) :
                new ObjectParameter("Parameter1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fxnExample_Result>("[POSEZ2UEntities].[fxnExample](@Parameter1)", parameter1Parameter);
        }
    
        public virtual int pos_th_SaveDataMapModifireToProduct(Nullable<int> productid, Nullable<int> userid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pos_th_SaveDataMapModifireToProduct", productidParameter, useridParameter);
        }
    
        public virtual ObjectResult<getModifireByProduct_Result> getModifireByProduct(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getModifireByProduct_Result>("getModifireByProduct", productidParameter);
        }
    
        public virtual ObjectResult<pos_th_GetAllListPermissionByDepartmentID_Result> pos_th_GetAllListPermissionByDepartmentID(Nullable<int> departmentid)
        {
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetAllListPermissionByDepartmentID_Result>("pos_th_GetAllListPermissionByDepartmentID", departmentidParameter);
        }
    
        public virtual ObjectResult<pos_th_GetDailySaleReport_Result> pos_th_GetDailySaleReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDailySaleReport_Result>("pos_th_GetDailySaleReport");
        }
    
        public virtual int pos_th_GetDataListShiftHistoryByUserID(Nullable<int> userid, Nullable<int> type)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pos_th_GetDataListShiftHistoryByUserID", useridParameter, typeParameter);
        }
    
        public virtual ObjectResult<pos_th_GetDetailDailyReport_Result> pos_th_GetDetailDailyReport(Nullable<int> paymenttypeid)
        {
            var paymenttypeidParameter = paymenttypeid.HasValue ?
                new ObjectParameter("paymenttypeid", paymenttypeid) :
                new ObjectParameter("paymenttypeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDetailDailyReport_Result>("pos_th_GetDetailDailyReport", paymenttypeidParameter);
        }
    
        public virtual ObjectResult<pos_th_GetDetailWeeklyReport_Result> pos_th_GetDetailWeeklyReport(Nullable<int> paymenttypeid)
        {
            var paymenttypeidParameter = paymenttypeid.HasValue ?
                new ObjectParameter("paymenttypeid", paymenttypeid) :
                new ObjectParameter("paymenttypeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDetailWeeklyReport_Result>("pos_th_GetDetailWeeklyReport", paymenttypeidParameter);
        }
    
        public virtual ObjectResult<pos_th_GetWeeklySaleReport_Result> pos_th_GetWeeklySaleReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetWeeklySaleReport_Result>("pos_th_GetWeeklySaleReport");
        }
    
        public virtual int pos_th_SaveDataPermissionByDepartmet(Nullable<int> departmentid, Nullable<int> userid)
        {
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pos_th_SaveDataPermissionByDepartmet", departmentidParameter, useridParameter);
        }
    
        public virtual ObjectResult<pos_th_GetDataBackupDatabase_Result> pos_th_GetDataBackupDatabase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDataBackupDatabase_Result>("pos_th_GetDataBackupDatabase");
        }
    
        public virtual ObjectResult<pos_th_GetDataProductAndModifire_Result> pos_th_GetDataProductAndModifire()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDataProductAndModifire_Result>("pos_th_GetDataProductAndModifire");
        }
    
        public virtual ObjectResult<pos_th_GetDataSaleByAccount_Result> pos_th_GetDataSaleByAccount(string dateselect, Nullable<int> type)
        {
            var dateselectParameter = dateselect != null ?
                new ObjectParameter("dateselect", dateselect) :
                new ObjectParameter("dateselect", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDataSaleByAccount_Result>("pos_th_GetDataSaleByAccount", dateselectParameter, typeParameter);
        }
    
        public virtual ObjectResult<pos_th_GetDataSaleByCard_Result> pos_th_GetDataSaleByCard(string dateselect, Nullable<int> type)
        {
            var dateselectParameter = dateselect != null ?
                new ObjectParameter("dateselect", dateselect) :
                new ObjectParameter("dateselect", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDataSaleByCard_Result>("pos_th_GetDataSaleByCard", dateselectParameter, typeParameter);
        }
    
        public virtual ObjectResult<pos_th_GetDataSummaryReport_Result> pos_th_GetDataSummaryReport(string dateselect, Nullable<int> type)
        {
            var dateselectParameter = dateselect != null ?
                new ObjectParameter("dateselect", dateselect) :
                new ObjectParameter("dateselect", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDataSummaryReport_Result>("pos_th_GetDataSummaryReport", dateselectParameter, typeParameter);
        }
    
        public virtual ObjectResult<pos_th_GetDetailProductPrice_Result> pos_th_GetDetailProductPrice(Nullable<int> productpriceID)
        {
            var productpriceIDParameter = productpriceID.HasValue ?
                new ObjectParameter("productpriceID", productpriceID) :
                new ObjectParameter("productpriceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDetailProductPrice_Result>("pos_th_GetDetailProductPrice", productpriceIDParameter);
        }
    
        public virtual ObjectResult<pos_th_GetListProductPrice_Result> pos_th_GetListProductPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetListProductPrice_Result>("pos_th_GetListProductPrice");
        }
    
        public virtual ObjectResult<pos_th_GetQTYGroupSaleReport_Result> pos_th_GetQTYGroupSaleReport(string dateselect, Nullable<int> type)
        {
            var dateselectParameter = dateselect != null ?
                new ObjectParameter("dateselect", dateselect) :
                new ObjectParameter("dateselect", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetQTYGroupSaleReport_Result>("pos_th_GetQTYGroupSaleReport", dateselectParameter, typeParameter);
        }
    
        public virtual ObjectResult<pos_th_GetQTYItemSaleReport_Result> pos_th_GetQTYItemSaleReport(string dateselect, Nullable<int> type)
        {
            var dateselectParameter = dateselect != null ?
                new ObjectParameter("dateselect", dateselect) :
                new ObjectParameter("dateselect", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetQTYItemSaleReport_Result>("pos_th_GetQTYItemSaleReport", dateselectParameter, typeParameter);
        }
    
        public virtual ObjectResult<pos_th_GetReportSaleByStaff_Result> pos_th_GetReportSaleByStaff(string dateselect, Nullable<int> type)
        {
            var dateselectParameter = dateselect != null ?
                new ObjectParameter("dateselect", dateselect) :
                new ObjectParameter("dateselect", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetReportSaleByStaff_Result>("pos_th_GetReportSaleByStaff", dateselectParameter, typeParameter);
        }
    
        public virtual ObjectResult<pos_th_GetShiftReport_Result> pos_th_GetShiftReport(string dateselect)
        {
            var dateselectParameter = dateselect != null ?
                new ObjectParameter("dateselect", dateselect) :
                new ObjectParameter("dateselect", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetShiftReport_Result>("pos_th_GetShiftReport", dateselectParameter);
        }
    
        public virtual ObjectResult<pos_th_SearchProduct_Result> pos_th_SearchProduct(string txtsearch, Nullable<int> type)
        {
            var txtsearchParameter = txtsearch != null ?
                new ObjectParameter("txtsearch", txtsearch) :
                new ObjectParameter("txtsearch", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_SearchProduct_Result>("pos_th_SearchProduct", txtsearchParameter, typeParameter);
        }
    
        public virtual ObjectResult<LISTTKA_Result> LISTTKA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LISTTKA_Result>("LISTTKA");
        }
    
        public virtual int UpdateToServer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateToServer");
        }
    
        public virtual ObjectResult<pos_th_GetDataSummaryReportNew_Result> pos_th_GetDataSummaryReportNew(string dateselect, Nullable<int> type)
        {
            var dateselectParameter = dateselect != null ?
                new ObjectParameter("dateselect", dateselect) :
                new ObjectParameter("dateselect", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pos_th_GetDataSummaryReportNew_Result>("pos_th_GetDataSummaryReportNew", dateselectParameter, typeParameter);
        }
    }
}
