//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTemp
    {
        public int ShiftHistoryID { get; set; }
        public int StaffID { get; set; }
        public string ShiftName { get; set; }
        public Nullable<System.DateTime> StartShift { get; set; }
        public Nullable<System.DateTime> EndShift { get; set; }
        public Nullable<int> Status { get; set; }
        public double CashStart { get; set; }
        public double CashEnd { get; set; }
        public double SafeDrop { get; set; }
        public string UserName { get; set; }
    }
}
