//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOID_ITEM_HISTORY
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ModifireID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> Qty { get; set; }
        public string FloorID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
